- name: Installation of my web-server
  hosts: all
  tasks:
    - name: install web package
      package:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: start apache2
      systemd:
        name: nginx
        state: started
      when: ansible_os_family == "Debian"